apiVersion: v1
kind: Pod
metadata:
  name: conv-app
  labels:
    components: frontend
    version: v1
spec:
  containers:
    - name: conv-app
      image: antonlarichev/conv-app:1.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
  restartPolicy: OnFailure